stages:
  - build
  - publish
  - deploy

build:
  stage: build
  tags:
    - all
  script:
    - cd social_project
    - chmod +x ./gradlew
    - ./gradlew clean
    - ./gradlew build -x test
  artifacts:
    paths:
      - social_project/build/libs/*.jar
    expire_in: 1 day
  after_script:
  only:
    - dev
    - master

publish:
  stage: publish
  tags:
    - all
  image: docker:latest
  variables:
    DOCKER_TLS_CERTDIR: ""
    DOCKER_DRIVER: overlay2
  dependencies:
    - build
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD 
  script:
    - cd social_project
    - export VERSION=${CI_COMMIT_SHA:0:8}
    - docker build -t $CI_REGISTRY_USER/$CI_REGISTRY_IMAGE:$VERSION -t $CI_REGISTRY_USER/$CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_USER/$CI_REGISTRY_IMAGE:$VERSION
    - docker push $CI_REGISTRY_USER/$CI_REGISTRY_IMAGE:latest
  only:
    - dev
    - master

deploy:
  stage: deploy
  image: docker:latest
  tags:
    - all
  variables:
    DOCKER_TLS_CERTDIR: ""
    DOCKER_DRIVER: overlay2
  before_script:
    - apk add --no-cache curl
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
  script:
    - cd social_project
    - docker-compose -f docker-compose.prod.yml down || echo "Down command failed, continuing..."
    - docker-compose -f docker-compose.prod.yml up -d
    - sh ci-cd-success-notification.sh
  only:
    - dev
    - master
