stages:
  - deploy

# Deploy job (docker-compose를 사용하여 서비스 시작)
deploy-job:
  stage: deploy
  image: docker:latest  # Docker 이미지를 사용
  services:
    - docker:19.03.12-dind  # Docker-in-Docker 서비스 활성화
  before_script:
    - apk add --no-cache py3-pip  # Alpine 기반 이미지에서 pip 설치
    - pip install docker-compose  # docker-compose 설치
  script:
    - docker-compose -f docker-compose.yml up -d  # Docker Compose를 사용하여 서비스 시작
