version: '3.8'

services:
  # MySQL 서비스
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: elice1234
      MYSQL_DATABASE: mydb
      MYSQL_USER: elice
      MYSQL_PASSWORD: elice1234
    ports:
      - "3306:3306"  # 외부에서 3307 포트로 접속


  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_DATABASE: chat
    ports:
      - "27017:27017"


  # Redis 서비스
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    command: redis-server --requirepass elice1234  # Redis 비밀번호 설정