version: '3.8'

services:
  # MySQL 서비스
  mysql:
    container_name: mysql
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: elice1234
      MYSQL_DATABASE: mydb
      MYSQL_USER: elice
      MYSQL_PASSWORD: elice1234
    ports:
      - "3306:3306"
    networks:
      - dev-network

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_DATABASE: chat
    ports:
      - "27017:27017"
    networks:
      - dev-network

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    command: redis-server --requirepass elice1234
    networks:
      - dev-network

networks:
  dev-network:
    driver: bridge 