version: '3.8'

services:
  # MySQL 서비스
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: elice1234
      MYSQL_DATABASE: mydb
      MYSQL_USER: elice
      MYSQL_PASSWORD: elice1234
    ports:
      - "3306:3306"  # 외부에서 3307 포트로 접속
    volumes:
      - ./mysql_data:/var/lib/mysql  # MySQL 데이터 지속성


  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: elice
      MONGO_INITDB_ROOT_PASSWORD: elice1234
      MONGO_INITDB_DATABASE: chatdb
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb_data:/data/db

  # Redis 서비스
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis_data:/data
    command: redis-server --requirepass elice1234  # Redis 비밀번호 설정